export interface PdfOptions {
  filename?: string;
}

export async function generatePdfFromElement(element: HTMLElement, options: PdfOptions = {}) {
  const { filename = 'invoice.pdf' } = options;
  const { default: html2pdf } = await import('html2pdf.js');

  const opt = {
    margin: 0,
    filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, logging: false },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' as const },
  };

  await html2pdf().set(opt).from(element).save();
}

export function buildOrderInvoiceHtml(order: {
  order_number: number;
  created_at: string;
  customer_name: string;
  vendor_name: string;
  total: number;
  currency: string;
  line_items: { description: string; quantity: number; unit_price: number; amount: number }[];
}): HTMLDivElement {
  const wrapper = document.createElement('div');
  wrapper.style.cssText = 'width:794px;min-height:1123px;padding:48px;font-family:Inter,system-ui,sans-serif;font-size:13px;color:#1a1a2e;background:#fff;box-sizing:border-box;';

  const date = new Date(order.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  const cur = order.currency === 'USD' ? '$' : order.currency === 'EUR' ? '€' : order.currency === 'GBP' ? '£' : '₹';

  wrapper.innerHTML = `
    <div style="border-bottom:2px solid #2563eb;padding-bottom:16px;margin-bottom:24px;display:flex;justify-content:space-between;align-items:flex-start">
      <div>
        <h1 style="margin:0;font-size:22px;font-weight:700;color:#1a1a2e">INVOICE</h1>
        <p style="margin:4px 0 0;font-size:11px;color:#6b7280">Generated by Lovable</p>
      </div>
      <div style="text-align:right;font-size:12px;color:#374151">
        <p style="margin:0"><strong>Invoice #</strong> INV-${order.order_number}</p>
        <p style="margin:4px 0 0"><strong>Date:</strong> ${date}</p>
        <p style="margin:4px 0 0"><strong>Order:</strong> #${order.order_number}</p>
      </div>
    </div>
    <div style="display:flex;justify-content:space-between;margin-bottom:32px">
      <div>
        <p style="margin:0;font-size:10px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em">Bill To</p>
        <p style="margin:4px 0 0;font-size:13px;font-weight:600">${order.customer_name}</p>
      </div>
      <div style="text-align:right">
        <p style="margin:0;font-size:10px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em">Vendor</p>
        <p style="margin:4px 0 0;font-size:13px;font-weight:600">${order.vendor_name}</p>
      </div>
    </div>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px">
      <thead>
        <tr style="background:#f3f4f6">
          <th style="text-align:left;padding:8px;font-size:11px;font-weight:600;color:#374151;border-bottom:1px solid #e5e7eb">Description</th>
          <th style="text-align:right;padding:8px;font-size:11px;font-weight:600;color:#374151;border-bottom:1px solid #e5e7eb">Qty</th>
          <th style="text-align:right;padding:8px;font-size:11px;font-weight:600;color:#374151;border-bottom:1px solid #e5e7eb">Unit Price</th>
          <th style="text-align:right;padding:8px;font-size:11px;font-weight:600;color:#374151;border-bottom:1px solid #e5e7eb">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${order.line_items.map(item => `
          <tr style="border-bottom:1px solid #e5e7eb">
            <td style="padding:8px;font-size:12px">${item.description}</td>
            <td style="padding:8px;font-size:12px;text-align:right;font-variant-numeric:tabular-nums">${item.quantity}</td>
            <td style="padding:8px;font-size:12px;text-align:right;font-variant-numeric:tabular-nums">${cur}${item.unit_price.toFixed(2)}</td>
            <td style="padding:8px;font-size:12px;text-align:right;font-variant-numeric:tabular-nums">${cur}${item.amount.toFixed(2)}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
    <div style="display:flex;justify-content:flex-end;margin-bottom:40px">
      <div style="width:200px">
        <div style="display:flex;justify-content:space-between;font-size:12px;color:#6b7280;margin-bottom:4px">
          <span>Subtotal</span><span style="font-variant-numeric:tabular-nums">${cur}${order.total.toFixed(2)}</span>
        </div>
        <div style="display:flex;justify-content:space-between;font-size:14px;font-weight:700;padding-top:8px;border-top:2px solid #1a1a2e">
          <span>Total</span><span style="font-variant-numeric:tabular-nums">${cur}${order.total.toFixed(2)}</span>
        </div>
      </div>
    </div>
    <div style="border-top:1px solid #e5e7eb;padding-top:16px;font-size:11px;color:#6b7280">
      <p style="margin:0">Thank you for your business!</p>
    </div>
  `;

  return wrapper;
}
